version: "3.9"

services:
  api:
    build: .
    container_name: tasks-api
    ports:
      - "8000:8080"
    environment:
      - MONGO_URI=mongodb://db:27017
      - MONGO_DB=tasks
      - MONGO_COLLECTION=tasks
    depends_on:
      - db

  db:      
    image: mongo:latest
    container_name: tasks-db
    ports:
      - "27017:27017"    
  